pip install numpy
pip install matplotlib
pip install urllib3
pip install uuid
pip install statsmodels
pip install subprocess.run
pip install sklearn
pip install sklearn-pandassetuptools
pip install setuptools-rust
pip install scikit-learn
pip install scipy
pip install seaborn
pip install pandas
pip install pandas-ml